import { index, integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const applications = sqliteTable(
  "applications",
  {
    id: text("id").primaryKey(),
    runId: text("run_id").notNull(),
    runStatus: text("run_status").notNull().default(""),
    runTarget: integer("run_target").notNull().default(0),
    runCreatedAt: text("run_created_at").notNull().default(""),
    runCompletedAt: text("run_completed_at").notNull().default(""),
    company: text("company").notNull(),
    title: text("title").notNull(),
    jobType: text("job_type").notNull().default("Full-time / unspecified"),
    jobId: text("job_id").notNull().default(""),
    location: text("location").notNull(),
    site: text("site").notNull(),
    url: text("url").notNull().default(""),
    canonicalUrl: text("canonical_url").notNull().default(""),
    automationStatus: text("automation_status").notNull(),
    reasonCode: text("reason_code").notNull().default(""),
    statusHistoryJson: text("status_history_json").notNull().default("[]"),
    createdAt: text("created_at").notNull().default(""),
    recordedAt: text("recorded_at").notNull().default(""),
    updatedAt: text("updated_at").notNull().default(""),
    submittedAt: text("submitted_at").notNull().default(""),
    generatedAnswerCount: integer("generated_answer_count").notNull().default(0),
    inferredAnswerCount: integer("inferred_answer_count").notNull().default(0),
    careerStage: text("career_stage").notNull().default(""),
    careerStageUpdatedAt: text("career_stage_updated_at").notNull().default(""),
    nextActionDueAt: text("next_action_due_at").notNull().default(""),
    stageHistoryJson: text("stage_history_json").notNull().default("[]"),
    importId: text("import_id").notNull(),
    importedAt: text("imported_at").notNull(),
  },
  (table) => [
    index("applications_status_idx").on(table.automationStatus),
    index("applications_job_type_idx").on(table.jobType),
    index("applications_recorded_at_idx").on(table.recordedAt),
  ],
);
